import pathlib,re,json
root=pathlib.Path('public')
for f in root.rglob('*.html'):
 text=f.read_text(encoding='utf-8')
 title=re.search(r'<title>(.*?)</title>',text).group(1)
 text=text.replace('</head>',f'  <meta name="description" content="{title} — research, projects and academic resources.">\n  <link rel="stylesheet" href="/css/platform.css">\n  <script defer src="/js/accessibility.js"></script>\n</head>')
 text=text.replace("onerror=\"this.src=", "onerror=\"this.onerror=null;this.src=")
 if f.name=='pupil.html':text=text.replace('onclick="togglePupil(this)"','onclick="togglePupil(this, event)" role="button" tabindex="0" aria-expanded="false"').replace('function togglePupil(card) {','function togglePupil(card, event) {')
 if f.name=='schedule.html':text=text.replace('<iframe','<iframe title="Research calendar" loading="lazy"')
 if f.name=='index.html':
  text=text.replace('</body>','<script defer src="/js/home-data.js"></script>\n</body>')
  text=re.sub(r'(<span class="stat-number" data-target="(\d+)">)0',lambda m:m[1]+m[2],text)
  text=text.replace("if (!window.d3 || !d3.geoOrthographic) { return setTimeout(start, 120); }", "if (!window.d3 || !d3.geoOrthographic) { if (++attempts < 50) setTimeout(start, 120); return; }")
  text=text.replace('function start() {','let attempts = 0;\n    function start() {',1)
  text=text.replace('function draw(t) {','let frame = 0, onScreen = false;\n      const reduced = window.matchMedia("(prefers-reduced-motion: reduce)");\n      function draw(t) {')
  text=text.replace('requestAnimationFrame(draw);','if (onScreen && !document.hidden && !reduced.matches) frame = requestAnimationFrame(draw);')
  text=text.replace("canvas.addEventListener('wheel'", "const restart = () => { cancelAnimationFrame(frame); draw(performance.now()); };\n      new IntersectionObserver(entries => { onScreen = entries[0].isIntersecting; restart(); }).observe(canvas);\n      document.addEventListener('visibilitychange', restart);\n      reduced.addEventListener('change', restart);\n      canvas.addEventListener('wheel'")
  text=text.replace('idle = 0;\n      }, { passive: false });','idle = 0; restart();\n      }, { passive: false });')
  text=text.replace('lastX = e.clientX; lastY = e.clientY;\n        }','lastX = e.clientX; lastY = e.clientY; restart();\n        }')
 if f.name=='overleaf.html':
  text=text.replace("navigator.clipboard.writeText(code).then(() => {", "(navigator.clipboard ? navigator.clipboard.writeText(code) : Promise.reject()).then(() => {")
  text=text.replace("btn.textContent = 'Copy'; }, 1500);\n      });", "btn.textContent = 'Copy'; }, 1500);\n      }).catch(() => { btn.textContent = 'Select text to copy'; });")
  text=text.replace('class="ov-lightbox" id="ovLightbox"','class="ov-lightbox" role="dialog" aria-modal="true" aria-label="Screenshot preview" tabindex="-1" id="ovLightbox"')
 text=text.replace('<input type="text" id="tierSearch"','<input aria-label="Search conferences" type="text" id="tierSearch"').replace('<input type="text" id="jSearch"','<input aria-label="Search journals" type="text" id="jSearch"')
 f.write_text(text,encoding='utf-8')
p=root/'js/sidebar.js';text=p.read_text(encoding='utf-8');text=re.sub(r"const basePath = .*?;", "const basePath = '/';", text)
text=text.replace("sidebar.id = 'sidebar';", "sidebar.id = 'sidebar';\n  sidebar.inert = true;\n  sidebar.setAttribute('aria-label', 'Main navigation');\n  hamburger.setAttribute('aria-controls', 'sidebar');\n  hamburger.setAttribute('aria-expanded', 'false');")
text=text.replace("overlay.classList.toggle('active');", "overlay.classList.toggle('active');\n    const open = sidebar.classList.contains('active');\n    sidebar.inert = !open;\n    hamburger.setAttribute('aria-expanded', String(open));\n    if (open) sidebar.querySelector('a,button')?.focus();\n    else hamburger.focus();")
text=text.replace("hamburger.addEventListener('click', toggleSidebar);", "document.addEventListener('keydown', e => { if (e.key === 'Escape' && sidebar.classList.contains('active')) toggleSidebar(); });\n  hamburger.addEventListener('click', toggleSidebar);")
p.write_text(text,encoding='utf-8')
pages=json.loads(pathlib.Path('seed/pages.json').read_text(encoding='utf-8'))
(root/'sitemap.xml').write_text('<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://sjhwang-research-replica.kjh861213.chatgpt.site'+p['path']+'</loc></url>' for p in pages)+'</urlset>',encoding='utf-8')
(root/'robots.txt').write_text('User-agent: *\nDisallow: /admin/\nDisallow: /api/\n',encoding='utf-8')
print('Enhanced all original pages, menu paths and fallback behavior.')
