import fs from 'node:fs';
import path from 'node:path';
import p from '../seed/researcher.json' with {type:'json'};
const root=path.resolve('public');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const write=(file,text)=>{fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),text)};
const nav=[['/','홈'],['/pages/about.html','소개'],['/pages/research.html','연구'],['/pages/projects.html','프로젝트'],['/pages/experience.html','학력 · 경력'],['/pages/patents.html','지식재산'],['/pages/publications.html','논문 · 자료'],['/pages/conference-tier.html','학회 탐색'],['/pages/journal.html','저널 탐색'],['/pages/assistant.html','연구 도우미'],['/pages/contact.html','연락']];
const cards=p.research.map((r,i)=>`<a class="research-card kim-card" href="/pages/research.html#${r.id}"><span class="kim-overline">0${i+1} / ${esc(r.status)}</span><h3>${esc(r.title)}</h3><p class="kim-subtitle">${esc(r.subtitle)}</p><p>${esc(r.description)}</p><div class="kim-tags">${r.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><span class="kim-arrow" aria-hidden="true">↗</span></a>`).join('');
const education=p.education.map(r=>`<article class="kim-row"><time>${esc(r.date)}</time><div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div></article>`).join('');
const milestones=[...(p.companyCredentials??[]),...(p.career??[]),...p.milestones].map(r=>{const link=r.url?` <a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.linkLabel??'공식 자료')} ↗</a>`:'';return `<article class="kim-row"><time>${esc(r.date)}</time><div><h3>${esc(r.title)}${r.status?` (${esc(r.status)})`:''}</h3><p>${esc(r.description)}${link}</p></div></article>`}).join('');
const footer=`<footer class="kim-footer"><a href="/">김재환 <span>Jaehwan Kim</span></a><p>XAIKOREA · AI Research & Engineering</p><a href="mailto:${p.email}">${p.email}</a><p class="kim-small">© ${new Date().getFullYear()} Jaehwan Kim. <a href="/pages/sources.html">프로필 자료 기준</a></p></footer>`;
function shell(title,body,home=false){return `<!DOCTYPE html><html lang="ko" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="김재환 XAIKOREA 대표이사 겸 AI 연구원의 개인 연구자 플랫폼. CLOA, TAXiA, KorTaxArena와 세무회계 AI 연구."><title>${esc(title)} | 김재환 · Jaehwan Kim</title><link rel="icon" href="/assets/kim-mark.svg"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/kim.css"><script src="/js/theme.js" defer></script><script src="/js/sidebar.js" defer></script><script src="/js/kim.js" defer></script></head><body><a class="kim-skip" href="#mainContent">본문으로 이동</a><header class="kim-top"><a href="/">JK<span>김재환 / RESEARCH</span></a><a href="/pages/contact.html">협업 문의 ↗</a></header><main id="mainContent" class="main-content visible">${home?body:`<div class="kim-page"><p class="kim-overline">JAEHWAN KIM / RESEARCH PLATFORM</p><h1>${esc(title)}</h1>${body}</div>`}</main>${footer}</body></html>`}
const intro=`<div class="intro" id="intro"><div class="intro-content"><svg class="intro-svg" viewBox="0 0 600 320"><text class="intro-line line-1" x="300" y="95">Jaehwan</text><text class="intro-line line-2" x="300" y="185">Kim</text><text class="intro-line line-3" x="300" y="275">Research</text></svg></div></div>`;
write('index.html',shell('개인 연구자 플랫폼',intro+`<section class="hero kim-hero" id="hero"><canvas id="particleCanvas" aria-hidden="true"></canvas><div class="hero-content"><div class="hero-greeting animate-in">RESEARCHER · FOUNDER</div><h1 class="hero-name animate-in delay-1"><span class="gradient-text">김재환</span><span class="kim-english">Jaehwan Kim</span></h1><p class="hero-tagline animate-in delay-2">근거를 연결하는 AI,<br>실무에서 신뢰할 수 있는 기술.</p><p class="hero-identity animate-in delay-2">XAIKOREA 대표이사 겸 AI 연구원<br>aSSIST AI융합 · SDG 복수학위 박사과정</p><div class="hero-keywords animate-in delay-3"><span class="hero-keyword">Grounded AI</span><span>/</span><span class="hero-keyword">Tax & Accounting</span><span>/</span><span class="hero-keyword">LLM Evaluation</span></div><div class="hero-stats animate-in delay-3"><div class="stat"><span class="stat-number" data-target="3">3</span><span class="stat-label">Research & Products</span></div><div class="stat"><span class="stat-number" data-target="3">3</span><span class="stat-label">기업 특허 출원</span></div><div class="stat"><span class="stat-number" data-target="2025">2025</span><span class="stat-label">XAIKOREA 설립</span></div></div><div class="hero-cta animate-in delay-4"><a href="#research" class="btn btn-primary">연구 살펴보기 ↗</a><a href="/pages/contact.html" class="btn btn-outline">협업 문의</a></div></div><a class="scroll-indicator" href="#about"><span>SCROLL TO EXPLORE ↓</span></a></section><section class="section" id="about"><div class="container"><h2 class="section-title"><span class="section-number">01.</span> About Me</h2><div class="kim-about"><div class="image-frame"><img class="profile-photo" src="/assets/jaehwan-kim.jpg" alt="김재환 대표 프로필" width="1682" height="2528"></div><div><p class="kim-overline">DOMAIN EXPERTISE × AI RESEARCH</p><h2>도메인의 깊이에서<br>AI의 신뢰성으로.</h2><p>${esc(p.intro)}</p><p>한국외국어대학교에서 경영전공 MBA를 취득하고, aSSIST에서 AI융합 박사과정 연구를 이어가고 있습니다.</p><a class="btn btn-outline" href="/pages/about.html">프로필 더 보기 ↗</a></div></div></div></section><section class="section" id="research"><div class="container"><h2 class="section-title"><span class="section-number">02.</span> Research & Projects</h2><p class="kim-section-intro">근거 기반 응답, 도메인 특화 AI, 그리고 모델 평가.</p><div class="kim-grid">${cards}</div></div></section><section class="section"><div class="container"><h2 class="section-title"><span class="section-number">03.</span> Journey</h2>${milestones}</div></section><section class="section" id="contact"><div class="container kim-contact"><p class="kim-overline">LET’S BUILD TRUSTWORTHY AI</p><h2>연구를 함께,<br>기술을 현실로.</h2><p>근거 기반 AI, 세무·회계 도메인 연구 및 산학 협력을 제안해 주세요.</p><a class="btn btn-primary" href="mailto:${p.email}">${p.email} ↗</a></div></section>`,true));
const pages={
'about':['소개',`<div class="kim-about"><div class="image-frame"><img src="/assets/jaehwan-kim.jpg" alt="김재환" class="profile-photo"></div><div><h2>${p.name} <small>${p.englishName}</small></h2><p class="kim-subtitle">${p.role}</p><p>${p.intro}</p><a class="btn btn-outline" href="mailto:${p.email}">${p.email}</a></div></div><h2 class="kim-heading">학력</h2>${education}<h2 class="kim-heading">연구와 실무</h2><div class="kim-grid">${cards}</div>`],
'research':['연구',p.research.map(r=>`<article class="kim-detail" id="${r.id}"><span class="kim-overline">${r.status}</span><h2>${r.title}</h2><h3>${r.subtitle}</h3><p>${r.description}</p><div class="kim-tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><p class="kim-small">자료 기준: ${r.source}</p></article>`).join('')],
'projects':['프로젝트',`<p class="kim-lead">XAIKOREA에서 연구와 제품화를 연결하는 세 가지 축.</p><div class="kim-grid">${cards}</div>`],
'experience':['학력 · 경력',`<p class="kim-lead">경영과 도메인 전문성을 AI 연구개발에 연결합니다.</p><h2 class="kim-heading">Education</h2>${education}<h2 class="kim-heading">Experience & Milestones</h2>${milestones}`],
'patents':['지식재산',`<p class="kim-lead">XAIKOREA의 AI 추론 관련 특허 출원 현황.</p>${p.patents.map((r,i)=>`<article class="kim-row"><time>${r.date}<br>${r.status}</time><div><h3>${r.title}</h3><p>회사소개서 기재 특허 ${i+1} / 3</p></div></article>`).join('')}<p class="kim-note">회사소개서에 기재된 출원번호: 10-2026-0036482 / 0036483 / 0036484. 개별 제목과 번호의 대응, 발명자 및 등록 상태는 이 페이지에서 단정하지 않습니다.</p>`],
'publications':['논문 · 연구 자료',`<p class="kim-lead">진행 중인 연구와 공개 자료를 정리하는 공간입니다.</p><article class="kim-detail"><span class="kim-overline">WORK IN PROGRESS</span><h2>KorTaxArena</h2><p>한국어 세무 도메인 LLM 벤치마킹 연구를 진행하고 있습니다.</p><p>현재 확인된 자료에는 공개 논문, DOI, 데이터셋 및 코드 저장소 링크가 없어 게재 실적을 등록하지 않았습니다.</p><a href="/pages/research.html#kortaxarena" class="btn btn-outline">연구 내용 보기 ↗</a></article>`],
'contact':['연락 · 협업',`<div class="kim-detail"><p class="kim-overline">RESEARCH COLLABORATION</p><h2>함께 연구할 주제를 기다립니다.</h2><p>근거 기반 AI와 RAG, 한국어 도메인 LLM 평가, 세무·회계 AI 제품 및 산학 공동연구.</p><a class="btn btn-primary" href="mailto:${p.email}">${p.email} ↗</a><p class="kim-small">XAIKOREA · 경기도 성남시</p></div>`],
'sources':['프로필 자료 기준',`<p class="kim-lead">제공된 자료에서 확인한 내용을 바탕으로 작성했습니다.</p><div class="kim-detail"><h2>자료 기준</h2><ul><li>XAIKOREA 회사소개서: 2026년 4월</li><li>재직증명서: 2026년 6월 26일</li><li>aSSIST 재학증명서: 2026년 5월 1일</li><li>aSSIST SDG 복수학위 사실확인서: 2026년 6월 5일</li><li>한국외국어대학교 MBA 학위증: 2025년 2월</li><li><a href="/documents/xaikorea-ai-membership-2026.pdf" target="_blank" rel="noopener">경기도 AI 멤버십 기업 인증서</a>: 2026년 9월 1일</li><li><a href="/documents/xaikorea-technology-leading-company-2026.pdf" target="_blank" rel="noopener">기술보호 선도기업 지정서</a>: 2026년 6월 11일</li></ul><p>학위 과정 재학과 학위 취득을 구분하며, 기업의 특허 출원을 개인의 등록 특허로 표시하지 않습니다. 학력·재직 증명서 원본은 공개하지 않으며, 공개 가능한 기업 인증서는 논문·자료 페이지에서 제공합니다.</p><p>학회·저널 탐색 자료는 참고용 원본 스냅샷으로, 최신 순위나 마감일을 보장하지 않습니다.</p></div>`],
'assistant':['연구 도우미',`<p class="kim-lead">프로필과 연구 자료에서 근거를 찾아봅니다.</p><div class="kim-detail"><form id="agentForm"><label for="question">질문</label><textarea id="question" maxlength="1000" required placeholder="CLOA와 KorTaxArena 연구를 소개해 주세요"></textarea><label for="agentMode">응답 방식</label><select id="agentMode"><option value="retrieval">자료 검색 · 모델 없이 이용</option value="ollama">AI 에이전트 · 관리자 로그인 필요</option></select><button class="btn btn-primary" type="submit">질문하기 ↗</button></form><p id="agentStatus" role="status"></p><div id="agentAnswer" aria-live="polite"></div><p class="kim-small">AI 모드는 서버의 Ollama 모델 연결이 필요합니다. <a href="/admin/">관리자 로그인</a></p></div><script src="/js/assistant.js" defer></script>`]
};
const known=new Set(['conference-tier.html','journal.html',...Object.keys(pages).map(x=>x+'.html')]);
for(const file of fs.readdirSync(path.join(root,'pages'),{recursive:true})){if(!String(file).endsWith('.html')||known.has(String(file)))continue;write('pages/'+file,shell('연구 플랫폼',`<p class="kim-lead">김재환 연구자의 연구·경력·프로젝트를 확인해 보세요.</p><div class="kim-grid">${cards}</div><p><a class="btn btn-outline" href="/pages/about.html">김재환 소개</a></p>`));}
for(const [key,[title,body]] of Object.entries(pages))write(`pages/${key}.html`,shell(title,body));
for(const name of ['conference-tier','journal']){const file=path.join(root,'pages',name+'.html');let h=fs.readFileSync(file,'utf8');h=h.replaceAll('Sunjun Hwang','김재환').replaceAll('sunjun7559@gmail.com',p.email).replaceAll('assets/favicon.png','assets/kim-mark.svg');h=h.replace('</head>','<link rel="stylesheet" href="/css/kim.css"></head>');h=h.replace('<body>','<body><p class="kim-catalog-note">학회·저널 참고 자료 · 원본 스냅샷 기준 · <a href="/">김재환 연구 플랫폼</a></p>');write('pages/'+name+'.html',h);}
write('js/sidebar.js',`document.addEventListener('DOMContentLoaded',()=>{const nav=${JSON.stringify(nav)};const button=document.createElement('button');button.className='hamburger visible';button.setAttribute('aria-label','메뉴 열기');button.setAttribute('aria-expanded','false');button.innerHTML='<span></span><span></span><span></span>';const overlay=document.createElement('div');overlay.className='sidebar-overlay';const panel=document.createElement('nav');panel.className='sidebar';panel.setAttribute('aria-label','주 메뉴');panel.innerHTML='<div class="sidebar-header"><div class="kim-nav-name">김재환<small>Jaehwan Kim</small></div></div><ul class="sidebar-menu">'+nav.map(([url,label])=>'<li><a class="menu-item" href="'+url+'"'+(location.pathname===url?' aria-current="page"':'')+'>'+label+'</a></li>').join('')+'</ul>';document.body.prepend(button,overlay,panel);function toggle(force){const open=force??!panel.classList.contains('active');[button,overlay,panel].forEach(e=>e.classList.toggle('active',open));button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');panel.inert=!open;if(open)panel.querySelector('a').focus();else button.focus()}panel.inert=true;button.onclick=()=>toggle();overlay.onclick=()=>toggle(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('active'))toggle(false)});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>toggle(false)));});`);
write('assets/kim-mark.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#6c63ff"/><text x="32" y="42" text-anchor="middle" font-family="sans-serif" font-weight="bold" font-size="30" fill="white">JK</text></svg>');
const old=JSON.parse(fs.readFileSync('seed/pages.json','utf8'));for(const r of old)r.title=r.path.includes('conference')?'학회 탐색 | 김재환':r.path.includes('journal')?'저널 탐색 | 김재환':'김재환 연구 플랫폼';for(const [key,[title]] of Object.entries(pages))if(!old.some(r=>r.path===`/pages/${key}.html`))old.push({path:`/pages/${key}.html`,title:title+' | 김재환'});fs.writeFileSync('seed/pages.json',JSON.stringify(old,null,2)+'\n');
console.log('Personalized home, all legacy HTML routes, navigation and '+Object.keys(pages).length+' profile pages.');
